# Site
name: "blog.zacdurham.com"
owner: "Zac Durham"
title: "blog.zacdurham.com"
description: ""
logo: 'assets/images/logo.jpg'
favicon: ''
baseurl: ''
google_analytics: 'G-YL462E9S68'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  zac:
    name: Zac Durham
    display_name: Zac
    avatar: assets/images/avatar.jpg
    email: zacdurham@gmail.com
    web: https://links.zacdurham.com
    instagram: https://instagram.com/zchef2k
    description: "Owner of this fine establishment. Curator of its code. <br />Overall nice guy."

page:
  comments: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
